#!/usr/bin/env bash
NPM_SHARE_BIN='/usr/local/share/npm/bin'

exists () {(
  IFS=:

  for d in $PATH; 
    do
      if [ "$d" == "$1" ]; 
        then 
          return 0; 
        fi
    done
  return 1
)}

if (! exists $NPM_SHARE_BIN )
  then
    export PATH="$PATH:$NPM_SHARE_BIN"
    sudo ln -s "$NPM_SHARE_BIN/pineapple" /usr/local/bin/pineapple
fi;

_papl() {
  COMPREPLY=()
  local word="${COMP_WORDS[COMP_CWORD]}"
  local command="${COMP_WORDS[1]}"

  echo $word
  echo $command

  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "$(papl commands)" -- "$word") )
  else
    local command="${COMP_WORDS[1]}"
    local completions="$(papl completions "$command")"
    COMPREPLY=( $(compgen -W "$completions" -- "$word") )
  fi
}

complete -F _papl papl