#!/usr/bin/env bash
cmd="";

command -v apt-get > /dev/null 2>&1 && {
  cmd="sudo apt-get";
}

command -v yum > /dev/null 2>&1 && {
  cmd="sudo yum";
}

command -v brew > /dev/null 2>&1 && {
  cmd="brew";
}

if [[ $cmd ]]; 
  then
    command -v ruby > /dev/null 2>&1 || {
      eval $cmd' install ruby';
    }
fi;

command -v gem > /dev/null 2>&1 && {
  command -v foreman > /dev/null 2>&1 || {
    sudo gem install foreman;
    exit;
  }
}

command -v npm > /dev/null 2>&1 && {
  sudo npm update pineapple -g
}