#!/usr/bin/env bash
cmd="";
if [ "$(whoami)" != "root" ]; then
  echo "Need sudo";
  exit 1;
fi;

command -v apt-get > /dev/null 2>&1 && {
  cmd="sudo apt-get";
}

command -v yum > /dev/null 2>&1 && {
  cmd="sudo yum";
}

command -v brew > /dev/null 2>&1 && {
  cmd="brew";
}

if [[ $cmd ]]; 
  then
    command -v ruby > /dev/null 2>&1 || {
      echo "Installing latest ruby..";
      eval $cmd' install ruby';
    }
fi;

command -v gem > /dev/null 2>&1 && {
  command -v foreman > /dev/null 2>&1 || {
    echo "Installing latest foreman gem..";
    sudo gem install foreman;
    exit;
  }
}

command -v npm > /dev/null 2>&1 && {
  echo "Installing latest pineapple..";
  sudo npm install pineapple -g
}